// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "coryptex.com/bot/vip-signal/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// SignalPublisher is an autogenerated mock type for the SignalPublisher type
type SignalPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, s
func (_m *SignalPublisher) Publish(ctx context.Context, s entities.Signal) error {
	ret := _m.Called(ctx, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Signal) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
